packages:
  - .

allowBuilds:
  es5-ext: false
  esbuild: true
  fsevents: false

minimumReleaseAgeExclude:
  - '@kubohiroya/sb3-toolchain@0.6.0'
  - '@kubohiroya/turbowarp-async-input@0.3.0'
  - '@kubohiroya/turbowarp-asset-manager@0.10.0'
  - '@kubohiroya/turbowarp-bubble@0.4.0'
  - '@kubohiroya/turbowarp-runtime-expression@0.3.0'
  - '@kubohiroya/turbowarp-svg-text@0.4.0'
  - '@kubohiroya/turbowarp-tmpose@1.7.4'

overrides:
  'scratch-vm>scratch-parser': 6.0.0
  'scratch-vm>uuid': 11.1.1
  'scratch-vm>worker-loader': '-'

peerDependencyRules:
  allowedVersions:
    scratch-render-fonts: 1.0.0
